/* eslint-disable */
/* tslint:disable */
// This file is generated. Do not edit it manually.

export type Output = {
  models: Array<
    {
      /** Unique identifier of the image generation model */
      id: string;
      name: string;
      /** Cost per image generation, in U.S. dollars */
      costPerImage: number;
      /** Available image sizes */
      sizes: string[];
      /** Default image size generated by model */
      defaultSize: string;
    } & { id: string }
  >;
};
