/* eslint-disable */
/* tslint:disable */
// This file is generated. Do not edit it manually.

import { z } from "@botpress/sdk";
export const output = {
  schema: z
    .object({
      models: z.array(
        z.intersection(
          z.object({
            id: z
              .string()
              .describe("Unique identifier of the image generation model"),
            name: z.string(),
            costPerImage: z
              .number()
              .describe("Cost per image generation, in U.S. dollars"),
            sizes: z.array(z.string()).describe("Available image sizes"),
            defaultSize: z
              .string()
              .describe("Default image size generated by model"),
          }),
          z.object({
            id: z.string(),
          }),
        ),
      ),
    })
    .catchall(z.never()),
};
