/* eslint-disable */
/* tslint:disable */
// This file is generated. Do not edit it manually.

export type Output = {
  /** Response ID from LLM provider */
  id: string;
  /** LLM provider name */
  provider: string;
  /** The name of the LLM model that was used */
  model: string;
  /** Array of generated message choices from the model */
  choices: Array<{
    type?: "text" | "tool_calls" | "tool_result" | "multipart";
    /** Required if `type` is "tool_calls" */
    toolCalls?: Array<{
      id: string;
      type: "function";
      function: {
        name: string;
        arguments: /** Some LLMs may generate invalid JSON for a tool call, so this will be `null` when it happens. */ {
          [key: string]: any;
        } | null;
      };
    }>;
    /** Required if `type` is "tool_result" */
    toolResultCallId?: string;
    content: /** Required unless `type` is "tool_call". If `type` is "multipart", this field must be an array of content objects. If `type` is "tool_result" then this field should be the result of the tool call (a plain string or a JSON-encoded array or object). If `type` is "tool_call" then the `toolCalls` field should be used instead. */
      | string
      | Array<{
          type: "text" | "image";
          /** Indicates the MIME type of the content. If not provided it will be detected from the content-type header of the provided URL. */
          mimeType?: string;
          /** Required if part type is "text" */
          text?: string;
          /** Required if part type is "image" */
          url?: string;
        }>
      | null;
    role: "assistant";
    index: number;
    stopReason:
      | "stop"
      | "max_tokens"
      | "tool_calls"
      | "content_filter"
      | "other";
  }>;
  /** A breakdown of token usage and cost information */
  usage: {
    /** Number of input tokens used by the model */
    inputTokens: number;
    /** Cost of the input tokens received by the model, in U.S. dollars */
    inputCost: number;
    /** Number of output tokens used by the model */
    outputTokens: number;
    /** Cost of the output tokens generated by the model, in U.S. dollars */
    outputCost: number;
  };
  /** Metadata added by Botpress */
  botpress: {
    /** Total cost of the content generation, in U.S. dollars */
    cost: number;
  };
};
